"""SteelIQ Plotter - Class-based plotting system for Steel-IQ visualizations.

This module provides a centralized, class-based approach to creating plots with
consistent styling, footers, legends, and color schemes across all Steel-IQ visualizations.
"""

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as mcolors
import matplotlib.patheffects as path_effects
import pandas as pd
import numpy as np
import logging
from matplotlib.figure import Figure
from matplotlib.ticker import MaxNLocator
from matplotlib.container import BarContainer
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
from pathlib import Path
from typing import Any, Optional, TYPE_CHECKING, cast
from dataclasses import dataclass, field
from datetime import datetime

if TYPE_CHECKING:
    from steelo.domain.models import PlotPaths
    from steelo.adapters.repositories.interface import PlantRepository

# Import global color schemes and constants
from steelo.utilities.plotting import (
    tech2colours,
    region2colours,
    _prepare_cost_curve_dataframe,
    _compute_market_clearing,
)
from steelo.domain.constants import T_TO_MT

logger = logging.getLogger(__name__)


# ============================================================================
# Configuration
# ============================================================================


@dataclass
class PlotConfig:
    """Configuration for consistent plot styling across all Steel-IQ visualizations.

    This class centralizes styling decisions for plots, making it easy to maintain
    consistency and customize appearance globally.

    Attributes:
        footer_template: Template string for plot footers. Use {date} and {version} placeholders.
        show_footer: Whether to display footer on plots
        legend_position: Legend position as (x, y) coordinates
        legend_loc: Legend location string (e.g., "upper left")
        legend_frameon: Whether to show frame around legend
        legend_fontsize: Font size for legend text
        default_dpi: Resolution for saved plots
        default_figsize_wide: Figure size for wide plots (width, height)
        default_figsize_square: Figure size for square plots (width, height)
        grid_alpha: Transparency of grid lines
        grid_linestyle: Style of grid lines
        tech_colors: Technology color mapping (will be copied from global tech2colours if not provided)
        region_colors: Region color mapping (will be copied from global region2colours if not provided)
        iron_ore_quality_colors: Iron ore quality color mapping (default: green/blue/red for high/mid/low)
        metallic_charge_colors: Metallic charge type color mapping (default: browns/oranges/grays)
    """

    footer_template: str = "Generated by Steel-IQ on {date}"
    show_footer: bool = True
    legend_position: tuple[float, float] = (1.05, 1)
    legend_loc: str = "upper left"
    legend_frameon: bool = True
    legend_fontsize: int = 10
    default_dpi: int = 300
    default_figsize_wide: tuple[int, int] = (12, 7)
    default_figsize_square: tuple[int, int] = (10, 10)
    grid_alpha: float = 0.3
    grid_linestyle: str = "--"
    tech_colors: dict[str, str] = field(default_factory=dict)
    region_colors: dict[str, str] = field(default_factory=dict)
    iron_ore_quality_colors: dict[str, str] = field(default_factory=dict)
    metallic_charge_colors: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        """Initialize color mappings from global defaults if not provided."""
        if not self.tech_colors:
            self.tech_colors = tech2colours.copy()
        if not self.region_colors:
            self.region_colors = region2colours.copy()
        if not self.iron_ore_quality_colors:
            # Iron ore: Progressive earth tones (light to dark = low to high quality)
            self.iron_ore_quality_colors = {
                "io_low": "#CD853F",  # peru (light brown) - lowest quality
                "io_mid": "#A0522D",  # sienna (medium brown) - mid quality
                "io_high": "#654321",  # dark brown - highest quality
            }
        if not self.metallic_charge_colors:
            # Metallic charges: Thematically grouped colors
            # - Scrap: Gray (recycled metal)
            # - DRI/HBI: Blue gradients (light=low, dark=high quality), mirroring io_* convention
            # - Pig iron/Hot metal: Dark grays (molten/intermediate products)
            self.metallic_charge_colors = {
                "scrap": "#708090",  # slate gray - recycled metal
                "dri_low": "#B0C4DE",  # light steel blue
                "dri_mid": "#4682B4",  # steel blue
                "dri_high": "#1F4E79",  # dark steel blue
                "hbi_low": "#CFE7F5",  # pale sky blue
                "hbi_mid": "#87CEEB",  # sky blue
                "hbi_high": "#3A8FBF",  # deeper sky blue
                "pig_iron": "#2F4F4F",  # dark slate gray - molten intermediate
                "hot_metal": "#696969",  # dim gray - molten metal (similar to pig iron)
            }


# ============================================================================
# Main Plotter Class
# ============================================================================


class SteelPlotter:
    """Main plotting class for Steel-IQ visualizations.

    This class provides a consistent interface for all Steel-IQ plots with
    centralized styling, footer management, and color scheme handling.

    Class attributes:
        EMISSIONS_SUBDIR: Subdirectory under ``plots_dir`` (sibling to PAM/GEO/TM)
            where emission charts are written. Kept centralised so call sites and
            tests reference one symbol.

    Example:
        >>> config = PlotConfig(footer_template="Generated by Steel-IQ v2.0 on {date}")
        >>> plotter = SteelPlotter(config, plot_paths)
        >>> plotter.plot_capex_by_technology(data_collector.trace_capex)
        >>> plotter.plot_emissions_by_technology(data_collector.trace_emissions)
    """

    EMISSIONS_SUBDIR = "emissions"
    COST_CURVES_SUBDIR = "cost_curves"

    def __init__(self, config: Optional[PlotConfig] = None, plot_paths: Optional["PlotPaths"] = None):
        """Initialize the SteelIQ plotter.

        Args:
            config: Plot configuration. If None, uses default PlotConfig.
            plot_paths: Output paths for saving plots. Required for saving plots.
        """
        self.config = config or PlotConfig()
        self.plot_paths = plot_paths
        self.logger = logging.getLogger(f"{__name__}.SteelPlotter")

    # ========================================================================
    # Helper Methods
    # ========================================================================

    def _apply_footer(self, fig: Figure) -> None:
        """Apply consistent footer to a figure.

        Args:
            fig: Matplotlib figure to add footer to
        """
        if not self.config.show_footer:
            return

        footer_text = self.config.footer_template.format(
            date=datetime.now().strftime("%Y-%m-%d"),
            version="1.0",  # TODO: Get from package version
        )

        fig.text(
            0.99,
            0.01,
            footer_text,
            ha="right",
            va="bottom",
            fontsize=8,
            color="gray",
            style="italic",
        )

    def _style_legend(self, ax, title: str = "", handles=None, labels=None, bbox_to_anchor=None):
        """Apply consistent legend styling to an axes.

        Args:
            ax: Matplotlib axes to style legend for
            title: Legend title
            handles: Optional custom legend handles
            labels: Optional custom legend labels
            bbox_to_anchor: Optional override for legend anchor; defaults to ``self.config.legend_position``.

        Returns:
            The Legend artist created (or None if no legend was produced).
        """
        anchor = bbox_to_anchor if bbox_to_anchor is not None else self.config.legend_position
        if handles is not None and labels is not None:
            legend = ax.legend(
                handles=handles,
                labels=labels,
                title=title,
                bbox_to_anchor=anchor,
                loc=self.config.legend_loc,
                frameon=self.config.legend_frameon,
                fontsize=self.config.legend_fontsize,
            )
        else:
            legend = ax.legend(
                title=title,
                bbox_to_anchor=anchor,
                loc=self.config.legend_loc,
                frameon=self.config.legend_frameon,
                fontsize=self.config.legend_fontsize,
            )
        if legend and title:
            legend.get_title().set_fontweight("bold")
        return legend

    def _save_figure(self, fig: Figure, filename: str, subdir: str = "pam_plots_dir") -> Path:
        """Save figure with consistent settings.

        Args:
            fig: Figure to save
            filename: Output filename
            subdir: Subdirectory attribute name from PlotPaths ("pam_plots_dir", "geo_plots_dir", etc.)

        Returns:
            Path where figure was saved

        Raises:
            ValueError: If plot_paths not set or subdirectory not found
        """
        if self.plot_paths is None:
            raise ValueError("plot_paths must be set to save figures")

        plot_dir = getattr(self.plot_paths, subdir, None)
        if plot_dir is None:
            raise ValueError(f"PlotPaths does not have attribute '{subdir}'")

        output_path = plot_dir / filename
        output_path.parent.mkdir(parents=True, exist_ok=True)

        self._apply_footer(fig)
        fig.savefig(output_path, dpi=self.config.default_dpi, bbox_inches="tight")
        plt.close(fig)

        self.logger.info(f"Saved plot to {output_path}")
        return output_path

    def _ensure_tech_color(self, tech: str) -> str:
        """Get color for technology, assigning default if not found.

        Args:
            tech: Technology name

        Returns:
            Color code for the technology
        """
        if tech not in self.config.tech_colors:
            self.config.tech_colors[tech] = "brown"
            self.logger.warning(f"No color defined for technology '{tech}', using brown")
        return self.config.tech_colors[tech]

    def _get_iron_ore_quality_color(self, quality: str) -> str:
        """Get color for iron ore quality, with fallback logic.

        Args:
            quality: Iron ore quality name

        Returns:
            Color code for the quality
        """
        quality_lower = quality.lower()
        # Try to match against known quality keys
        for key, color in self.config.iron_ore_quality_colors.items():
            if key in quality_lower:
                return color
        # Fallback to gray if not found
        self.logger.warning(f"No color defined for iron ore quality '{quality}', using gray")
        return "#808080"

    def _get_metallic_charge_color(self, charge_type: str) -> str:
        """Get color for metallic charge type, with fallback logic.

        Args:
            charge_type: Metallic charge type name

        Returns:
            Color code for the charge type
        """
        charge_lower = charge_type.lower()
        # Try to match against known charge type keys
        for key, color in self.config.metallic_charge_colors.items():
            if key in charge_lower:
                return color
        # Fallback: assign a consistent color based on hash
        if charge_lower not in self.config.metallic_charge_colors:
            # Use thematically consistent colors for unknown charge types
            # (grays, blues, and earth tones to match existing scheme)
            color_palette = [
                "#5F9EA0",  # cadet blue
                "#778899",  # light slate gray
                "#BC8F8F",  # rosy brown
                "#4169E1",  # royal blue
                "#A9A9A9",  # dark gray
                "#8FBC8F",  # dark sea green
            ]
            color = color_palette[hash(charge_lower) % len(color_palette)]
            self.config.metallic_charge_colors[charge_lower] = color
            self.logger.info(f"Assigned color {color} to metallic charge '{charge_type}'")
        return self.config.metallic_charge_colors[charge_lower]

    def _save_chart_data_to_csv(self, df: pd.DataFrame, filename: str, subdir: str = "pam_plots_dir") -> Optional[Path]:
        """Save chart data to CSV file.

        Args:
            df: DataFrame containing the chart data
            filename: Output filename (will replace .png with .csv)
            subdir: Subdirectory attribute name from PlotPaths

        Returns:
            Path where CSV was saved, or None if plot_paths not set
        """
        if self.plot_paths is None:
            self.logger.warning("plot_paths not set, skipping CSV export")
            return None

        plot_dir = getattr(self.plot_paths, subdir, None)
        if plot_dir is None:
            self.logger.warning(f"PlotPaths does not have attribute '{subdir}', skipping CSV export")
            return None

        # Replace .png extension with .csv
        csv_filename = filename.replace(".png", ".csv")
        output_path = plot_dir / csv_filename
        output_path.parent.mkdir(parents=True, exist_ok=True)

        try:
            df.to_csv(output_path, index=True)
            self.logger.info(f"Saved chart data to {output_path}")
            return output_path
        except Exception as e:
            self.logger.error(f"Failed to save CSV to {output_path}: {e}")
            return None

    def _ensure_y_axis_starts_at_zero(self, ax, upper_margin: float = 1.1):
        """Ensure y-axis starts at 0 and has appropriate upper limit.

        Args:
            ax: Matplotlib axis object
            upper_margin: Factor to multiply max value for upper limit (default: 1.1 = 10% margin)
        """
        current_ylim = ax.get_ylim()
        # Set lower limit to 0
        # For upper limit, use current max or add margin
        if current_ylim[1] > 0:
            ax.set_ylim(0, current_ylim[1] * upper_margin)
        else:
            # If no positive data, just set a reasonable range
            ax.set_ylim(0, 1)

    # ========================================================================
    # Plotting Methods
    # ========================================================================

    def plot_capex_by_technology(
        self,
        trace_capex: dict[int, dict[str, dict[str, float]]],
        iso3_filter: Optional[str] = None,
        export_csv: bool = True,
    ) -> Optional[Path]:
        """Plot total CAPEX investments by technology over years as a stacked bar chart.

        Args:
            trace_capex: Nested dict {year: {technology: {iso3: total_capex_usd}}}
            iso3_filter: Optional ISO3 country code to filter investments
            export_csv: If True, also export chart data to CSV (default: True)

        Returns:
            Path to saved plot, or None if no data to plot
        """
        if not trace_capex:
            self.logger.warning("No CAPEX data to plot")
            return None

        # Get full year range
        all_years = sorted(trace_capex.keys())
        if not all_years:
            return None

        year_min = min(all_years)
        year_max = max(all_years)
        full_year_range = list(range(year_min, year_max + 1))

        # Convert to DataFrame
        data_rows = []
        for year, techs in trace_capex.items():
            for tech, locations in techs.items():
                for iso3, capex in locations.items():
                    if iso3_filter is None or iso3 == iso3_filter:
                        data_rows.append({"year": year, "technology": tech, "iso3": iso3, "capex": capex})

        if not data_rows:
            self.logger.warning(f"No CAPEX data after filtering{f' for {iso3_filter}' if iso3_filter else ''}")
            return None

        df = pd.DataFrame(data_rows)
        df["capex_bn"] = df["capex"] / 1e9

        # Aggregate by year and technology
        capex_by_year_tech = df.groupby(["year", "technology"])["capex_bn"].sum().unstack("technology", fill_value=0)
        capex_by_year_tech = capex_by_year_tech.reindex(full_year_range, fill_value=0)

        # Ensure colors for all technologies
        for tech in capex_by_year_tech.columns:
            self._ensure_tech_color(tech)

        # Create plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        capex_by_year_tech.plot.bar(
            stacked=True,
            ax=ax,
            color=[self.config.tech_colors.get(tech, "brown") for tech in capex_by_year_tech.columns],
            width=0.8,
        )

        # Formatting
        location_str = f" in {iso3_filter}" if iso3_filter else " (Global)"
        ax.set_title(f"CAPEX Investments by Technology{location_str}", fontsize=14, fontweight="bold")
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel("Total CAPEX (Billion USD)", fontsize=12)
        legend_techs = self._legend_order_for_stack(capex_by_year_tech)
        tech_handles = [
            Patch(facecolor=self.config.tech_colors.get(tech, "brown"), label=tech) for tech in legend_techs
        ]
        self._style_legend(ax, title="Technology", handles=tech_handles, labels=legend_techs)
        ax.grid(axis="y", alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # X-axis formatting
        ax.set_xticks(range(len(full_year_range)))
        ax.set_xticklabels([str(year) for year in full_year_range], rotation=45, ha="right")

        # Thin out labels if too many years
        if len(full_year_range) > 20:
            step = 5 if len(full_year_range) > 50 else 2
            for i, label in enumerate(ax.xaxis.get_ticklabels()):
                if i % step != 0:
                    label.set_visible(False)

        # Add value labels on significant bars
        for container in ax.containers:
            if isinstance(container, BarContainer):
                heights = [patch.get_height() for patch in container.patches]
                labels = [f"{float(h):.1f}" if float(h) > 0.1 else "" for h in heights]
                ax.bar_label(container, labels=labels, label_type="center", fontsize=8, color="white", weight="bold")

        # Ensure y-axis starts at 0
        self._ensure_y_axis_starts_at_zero(ax)

        fig.tight_layout()

        # Save
        filename = f"capex_by_technology_and_year{'_' + iso3_filter if iso3_filter else ''}.png"

        # Export CSV if requested
        if export_csv:
            self._save_chart_data_to_csv(capex_by_year_tech, filename)

        return self._save_figure(fig, filename)

    def plot_emissions_by_technology(
        self,
        trace_emissions: dict[str, dict[int, dict[str, dict[str, float]]]],
        trace_production_by_product: Optional[dict[int, dict[str, float]]] = None,
        export_csv: bool = True,
    ) -> list[Path]:
        """Plot per-scope emissions by technology over time as five stacked area charts per boundary.

        Direct (excl. biogenic) and direct-with-biomass are alternative accountings of
        the same direct emissions and must never be summed together. This method emits
        five chart variants per emissions boundary present in the trace:

        - ``emissions_direct_by_technology__<boundary>.png`` — direct only
        - ``emissions_direct_with_biomass_by_technology__<boundary>.png`` — direct including biogenic
        - ``emissions_indirect_by_technology__<boundary>.png`` — indirect only
        - ``emissions_direct_plus_indirect_by_technology__<boundary>.png`` — direct on bottom, indirect (lighter) on top
        - ``emissions_direct_with_biomass_plus_indirect_by_technology__<boundary>.png`` — same with biogenic direct

        Args:
            trace_emissions: Nested dict {boundary: {year: {technology: {scope: emissions_tCO2e}}}},
                where scope is one of ``direct_ghg``, ``direct_with_biomass_ghg``,
                ``indirect_ghg``.
            trace_production_by_product: Optional {year: {"iron"/"steel": tonnes}}. When provided,
                each chart overlays iron and steel production as lines on a secondary axis.
            export_csv: If True, also export each chart's underlying data to CSV.

        Returns:
            List of paths to the saved plots (empty if there was nothing to plot).
        """
        if not trace_emissions:
            self.logger.warning("No emissions data to plot")
            return []

        production_df: Optional[pd.DataFrame] = None
        if trace_production_by_product:
            prod_rows = [
                {"year": year, "product": product, "production_mt": tonnes / 1e6}
                for year, by_product in trace_production_by_product.items()
                for product, tonnes in by_product.items()
            ]
            if prod_rows:
                production_df = (
                    pd.DataFrame(prod_rows).pivot(index="year", columns="product", values="production_mt").fillna(0.0)
                )

        saved: list[Path] = []
        for boundary, by_year in trace_emissions.items():
            saved.extend(
                self._plot_emissions_for_boundary(
                    boundary=boundary,
                    by_year=by_year,
                    production_df=production_df,
                    export_csv=export_csv,
                )
            )
        return saved

    def _plot_emissions_for_boundary(
        self,
        boundary: str,
        by_year: dict[int, dict[str, dict[str, float]]],
        production_df: Optional[pd.DataFrame],
        export_csv: bool,
    ) -> list[Path]:
        """Render the five emissions chart variants for a single boundary."""
        rows = []
        for year, by_tech in by_year.items():
            for tech, by_scope in by_tech.items():
                rows.append(
                    {
                        "year": year,
                        "technology": tech,
                        "direct_ghg": by_scope.get("direct_ghg", 0.0),
                        "direct_with_biomass_ghg": by_scope.get("direct_with_biomass_ghg", 0.0),
                        "indirect_ghg": by_scope.get("indirect_ghg", 0.0),
                    }
                )
        if not rows:
            return []

        df = pd.DataFrame(rows)
        for col in ("direct_ghg", "direct_with_biomass_ghg", "indirect_ghg"):
            df[col] = df[col] / 1e6  # tCO2e -> Mt CO2e

        direct_pivot = df.pivot(index="year", columns="technology", values="direct_ghg").fillna(0)
        direct_bio_pivot = df.pivot(index="year", columns="technology", values="direct_with_biomass_ghg").fillna(0)
        indirect_pivot = df.pivot(index="year", columns="technology", values="indirect_ghg").fillna(0)

        for tech in direct_pivot.columns:
            self._ensure_tech_color(tech)

        subtitle = f"Emissions boundary: {boundary.replace('_', ' ')}"
        suffix = boundary  # already snake_case; safe filename
        subdir = self.EMISSIONS_SUBDIR

        saved: list[Path] = []
        single_charts = [
            (
                "Direct emissions (excl. biogenic) by Technology",
                direct_pivot,
                f"{subdir}/emissions_direct_by_technology__{suffix}.png",
            ),
            (
                "Direct emissions (incl. biogenic) by Technology",
                direct_bio_pivot,
                f"{subdir}/emissions_direct_with_biomass_by_technology__{suffix}.png",
            ),
            (
                "Indirect emissions by Technology",
                indirect_pivot,
                f"{subdir}/emissions_indirect_by_technology__{suffix}.png",
            ),
        ]
        for title, pivot, filename in single_charts:
            path = self._plot_single_scope_emissions(
                pivot,
                title=title,
                subtitle=subtitle,
                filename=filename,
                export_csv=export_csv,
                production_df=production_df,
            )
            if path is not None:
                saved.append(path)

        combined_charts = [
            (
                "Direct (excl. biogenic) + Indirect emissions by Technology",
                direct_pivot,
                indirect_pivot,
                f"{subdir}/emissions_direct_plus_indirect_by_technology__{suffix}.png",
            ),
            (
                "Direct (incl. biogenic) + Indirect emissions by Technology",
                direct_bio_pivot,
                indirect_pivot,
                f"{subdir}/emissions_direct_with_biomass_plus_indirect_by_technology__{suffix}.png",
            ),
        ]
        for title, direct_part, indirect_part, filename in combined_charts:
            path = self._plot_combined_scope_emissions(
                direct_part,
                indirect_part,
                title=title,
                subtitle=subtitle,
                filename=filename,
                export_csv=export_csv,
                production_df=production_df,
            )
            if path is not None:
                saved.append(path)

        return saved

    def _plot_single_scope_emissions(
        self,
        pivot: pd.DataFrame,
        title: str,
        subtitle: str,
        filename: str,
        export_csv: bool,
        production_df: Optional[pd.DataFrame] = None,
    ) -> Optional[Path]:
        """Render one stacked-area chart for a single emissions scope.

        Args:
            pivot: DataFrame indexed by year, technologies as columns, values in Mt CO2e.
            title: Chart title.
            subtitle: Subtitle (typically the emissions boundary).
            filename: Output PNG filename (CSV uses the same stem).
            export_csv: If True, also write the pivot to CSV alongside the PNG.
            production_df: Optional iron/steel production overlay (Mt) keyed by year.

        Returns:
            Path to the saved figure, or None if there is nothing to plot.
        """
        if pivot.empty:
            return None

        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)
        colours = [self.config.tech_colors.get(tech, "brown") for tech in pivot.columns]
        self._plot_signed_stacked_area(ax, pivot, colours, alpha=0.8)
        production_handles = self._overlay_production_lines(ax, production_df)
        self._finalise_emissions_axes(ax, pivot.index, title=title, subtitle=subtitle)

        legend_techs = self._legend_order_for_stack(pivot)
        tech_handles = [
            Patch(facecolor=self.config.tech_colors.get(tech, "brown"), label=tech) for tech in legend_techs
        ]
        self._add_emissions_legends(ax, tech_handles, production_handles)
        fig.tight_layout()

        if export_csv:
            self._save_chart_data_to_csv(pivot, filename, subdir="plots_dir")
        return self._save_figure(fig, filename, subdir="plots_dir")

    def _plot_combined_scope_emissions(
        self,
        direct: pd.DataFrame,
        indirect: pd.DataFrame,
        title: str,
        subtitle: str,
        filename: str,
        export_csv: bool,
        production_df: Optional[pd.DataFrame] = None,
    ) -> Optional[Path]:
        """Render a stacked-area chart with direct on the bottom and indirect (lighter) on top per tech.

        The two pivots are joined column-wise into a single DataFrame whose columns
        alternate (direct, indirect) per technology so that matplotlib's area stack
        places the indirect band immediately above its corresponding direct band.

        Args:
            direct: Per-tech direct emissions (Mt CO2e), indexed by year.
            indirect: Per-tech indirect emissions (Mt CO2e), indexed by year. Must share columns/index with ``direct``.
            title: Chart title.
            subtitle: Subtitle (typically the emissions boundary).
            filename: Output PNG filename.
            export_csv: If True, also export the combined data.

        Returns:
            Path to the saved figure, or None if both inputs are empty.
        """
        if direct.empty and indirect.empty:
            return None

        techs = list(direct.columns.union(indirect.columns))
        years = direct.index.union(indirect.index)
        direct = direct.reindex(index=years, columns=techs).fillna(0)
        indirect = indirect.reindex(index=years, columns=techs).fillna(0)

        combined = pd.DataFrame(index=years)
        colours: list[Any] = []
        for tech in techs:
            base = self.config.tech_colors.get(tech, "brown")
            light = self._lighten_colour(base, factor=0.2)
            combined[f"{tech} (direct)"] = direct[tech]
            colours.append(base)
            combined[f"{tech} (indirect)"] = indirect[tech]
            colours.append(light)

        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)
        self._plot_signed_stacked_area(ax, combined, colours, alpha=0.85)
        production_handles = self._overlay_production_lines(ax, production_df)

        # Order by direct + indirect so techs visible only via their indirect band
        # (e.g. BOF, which has zero direct in responsible_steel) still appear in the legend.
        legend_techs = self._legend_order_for_stack(direct + indirect)
        tech_handles = [
            Patch(facecolor=self.config.tech_colors.get(tech, "brown"), label=tech) for tech in legend_techs
        ]
        tech_handles.append(Patch(facecolor="lightgrey", label="lighter shade = indirect"))

        self._finalise_emissions_axes(ax, years, title=title, subtitle=subtitle)
        self._add_emissions_legends(ax, tech_handles, production_handles)
        fig.tight_layout()

        if export_csv:
            self._save_chart_data_to_csv(combined, filename, subdir="plots_dir")
        return self._save_figure(fig, filename, subdir="plots_dir")

    def _finalise_emissions_axes(
        self,
        ax,
        years,
        title: str,
        subtitle: str,
    ) -> None:
        """Apply emissions-chart styling: title (bold), subtitle (smaller, lighter), axis labels, x-range, zero line."""
        ax.set_title(title, fontsize=14, fontweight="bold", pad=22)
        if subtitle:
            ax.text(
                0.5,
                1.005,
                subtitle,
                transform=ax.transAxes,
                ha="center",
                va="bottom",
                fontsize=9,
                fontweight="normal",
                color="dimgray",
            )
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel("Total Emissions (Mt CO2e)", fontsize=12)
        ax.grid(axis="y", alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        sorted_years = sorted(years)
        if sorted_years:
            ax.set_xlim(sorted_years[0], sorted_years[-1])
            ax.xaxis.set_major_locator(MaxNLocator(integer=True, nbins=min(len(sorted_years), 20)))

        ax.axhline(0, color="black", linewidth=0.6)

    def _overlay_production_lines(self, ax, production_df: Optional[pd.DataFrame]) -> list[Line2D]:
        """Draw iron and steel total production as lines on a secondary y-axis.

        Lines use a bright fill colour with a thicker black halo (via path effects) so
        they stay legible against any combination of stacked-area background colours.
        Returns legend proxies so the caller can append them to the main legend; a
        secondary-axis legend would otherwise sit alone in the corner.

        Args:
            ax: Primary emissions axis.
            production_df: Year-indexed Mt frame with at least one of {"iron", "steel"} columns.

        Returns:
            List of Line2D proxies (empty when no overlay was drawn).
        """
        if production_df is None or production_df.empty:
            return []

        ax2 = ax.twinx()
        ax2.set_ylabel("Total Production (Mt)", fontsize=12, color="black")
        product_styles = {
            "iron": {"color": "#FFD700", "label": "iron"},
            "steel": {"color": "#FFFFFF", "label": "steel"},
        }
        halo = [path_effects.Stroke(linewidth=2.5, foreground="black"), path_effects.Normal()]
        proxies: list[Line2D] = []
        for product, style in product_styles.items():
            if product not in production_df.columns:
                continue
            series = production_df[product].sort_index()
            ax2.plot(
                series.index,
                series.values,
                color=style["color"],
                linewidth=1.1,
                linestyle="-",
                path_effects=halo,
                label=style["label"],
            )
            proxies.append(
                Line2D(
                    [0],
                    [0],
                    color=style["color"],
                    linewidth=1.1,
                    linestyle="-",
                    path_effects=halo,
                    label=style["label"],
                )
            )

        ax2.set_ylim(bottom=0)
        return proxies

    @staticmethod
    def _legend_order_for_stack(pivot: pd.DataFrame) -> list[str]:
        """Order techs so the legend matches what the eye sees on the stacked chart.

        Visual reading top-to-bottom:
        - Top of chart = top of positive stack = the LAST positive column (alphabetically),
          since pandas stacks col[0] just above zero and col[N-1] at the top.
        - Bottom of chart = bottom of negative stack = the LAST negative column (it draws
          below earlier negative columns, so the last column ends up furthest below zero).

        We split present techs into positive-total and negative-total groups, then build
        the top-to-bottom legend order: positives in reverse column order (largest-stacked
        at top) followed by negatives in original column order (closest-to-zero first,
        most-negative last).

        Args:
            pivot: Year-indexed frame, one column per technology, values in Mt CO2e.

        Returns:
            Tech names ordered top-to-bottom for direct use as legend handle order.
            Excludes techs whose values are all zero.
        """
        columns = list(pivot.columns)
        totals = pivot.sum(axis=0)
        present = [t for t in columns if (pivot[t] != 0).any()]
        positive = [t for t in present if totals[t] >= 0]
        negative = [t for t in present if totals[t] < 0]
        return list(reversed(positive)) + negative

    def _add_emissions_legends(self, ax, tech_handles: list, production_handles: list) -> None:
        """Render two separate legend boxes: technology (top) and production volume (bottom).

        Splitting them keeps the technology list dense and avoids visual ambiguity about
        which axis the production lines belong to. Production legend is omitted when no
        production overlay was drawn.

        Args:
            ax: Primary emissions axis.
            tech_handles: Patch handles for the technology legend, in display order
                (bottom-of-stack tech last).
            production_handles: Line2D proxies for iron/steel production overlays
                (may be empty).
        """
        if production_handles:
            tech_anchor = (1.15, 1.0)
            production_anchor = (1.15, 0.0)
            production_loc = "lower left"
        else:
            tech_anchor = self.config.legend_position
            production_anchor = None
            production_loc = self.config.legend_loc

        tech_legend = self._style_legend(
            ax,
            title="Technology emissions (left axis)",
            handles=tech_handles,
            labels=[h.get_label() for h in tech_handles],
            bbox_to_anchor=tech_anchor,
        )

        if production_handles and tech_legend is not None:
            ax.add_artist(tech_legend)  # keep tech legend visible when adding the second
            production_legend = ax.legend(
                handles=production_handles,
                labels=[h.get_label() for h in production_handles],
                title="Production volumes (right axis)",
                bbox_to_anchor=production_anchor,
                loc=production_loc,
                frameon=self.config.legend_frameon,
                fontsize=self.config.legend_fontsize,
            )
            if production_legend is not None:
                production_legend.get_title().set_fontweight("bold")

    @staticmethod
    def _plot_signed_stacked_area(
        ax,
        pivot: pd.DataFrame,
        colours: list,
        alpha: float = 0.8,
    ) -> None:
        """Stacked area plot tolerant of mixed-sign columns.

        Pandas' ``DataFrame.plot.area`` rejects columns containing both positive and
        negative values (e.g. charcoal+CCS credits flipping year-on-year), so we split
        each column into positive and negative halves via ``clip`` and stack them
        separately. Positives accumulate upward from zero, negatives downward.

        After both halves are drawn we explicitly set the y-axis range from the stack
        totals: pandas' second call would otherwise call ``set_ylim(None, 0)`` and
        clobber the upper bound established by the positive half.

        Args:
            ax: Matplotlib axes to draw on.
            pivot: Year-indexed frame, one column per technology.
            colours: One colour per column, in the same order as ``pivot.columns``.
            alpha: Fill alpha applied to both halves.
        """
        positive = pivot.clip(lower=0)
        negative = pivot.clip(upper=0)
        has_positive = bool((positive != 0).any().any())
        has_negative = bool((negative != 0).any().any())
        if has_positive:
            positive.plot.area(ax=ax, color=colours, alpha=alpha, linewidth=0, legend=False)
        if has_negative:
            negative.plot.area(ax=ax, color=colours, alpha=alpha, linewidth=0, legend=False)

        y_max = float(positive.sum(axis=1).max()) if has_positive else 0.0
        y_min = float(negative.sum(axis=1).min()) if has_negative else 0.0
        margin = max(abs(y_max), abs(y_min)) * 0.05 or 1.0
        ax.set_ylim(y_min - margin if has_negative else 0, y_max + margin)

    @staticmethod
    def _lighten_colour(colour, factor: float = 0.5) -> tuple[float, float, float]:
        """Blend ``colour`` with white by ``factor`` to produce a lighter shade.

        Args:
            colour: Any matplotlib-recognised colour spec (hex, name, RGB tuple).
            factor: Blend strength in [0, 1]. 0 returns the original colour, 1 returns white.

        Returns:
            (r, g, b) tuple in [0, 1].
        """
        r, g, b = mcolors.to_rgb(colour)
        return (r + (1 - r) * factor, g + (1 - g) * factor, b + (1 - b) * factor)

    def plot_iron_ore_by_quality(
        self,
        trace_iron_ore: dict[int, dict[str, float]],
        export_csv: bool = True,
    ) -> Optional[Path]:
        """Plot iron ore consumption by quality over time as a stacked area chart.

        Args:
            trace_iron_ore: Nested dict {year: {quality: total_consumption_tonnes}}
            export_csv: If True, also export chart data to CSV (default: True)

        Returns:
            Path to saved plot, or None if no data to plot
        """
        if not trace_iron_ore:
            self.logger.warning("No iron ore data to plot")
            return None

        # Convert to DataFrame
        data_rows = []
        for year, qualities in trace_iron_ore.items():
            for quality, consumption in qualities.items():
                data_rows.append({"year": year, "quality": quality, "consumption": consumption})

        if not data_rows:
            return None

        df = pd.DataFrame(data_rows)
        df["consumption_mt"] = df["consumption"] / 1e6

        # Pivot
        df_pivot = df.pivot(index="year", columns="quality", values="consumption_mt")
        df_pivot = df_pivot.fillna(0)

        # Assign colors using centralized color mapping
        colors_for_plot = [self._get_iron_ore_quality_color(quality) for quality in df_pivot.columns]

        # Create plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        df_pivot.plot.area(
            ax=ax,
            color=colors_for_plot,
            alpha=0.8,
            linewidth=0,
        )

        # Formatting
        ax.set_title("Iron Ore Consumption by Quality Over Time", fontsize=14, fontweight="bold")
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel("Total Consumption (Mt)", fontsize=12)
        legend_qualities = self._legend_order_for_stack(df_pivot)
        quality_handles = [
            Patch(facecolor=self._get_iron_ore_quality_color(quality), label=quality) for quality in legend_qualities
        ]
        self._style_legend(ax, title="Quality", handles=quality_handles, labels=legend_qualities)
        ax.grid(axis="y", alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # X-axis formatting
        years = sorted(df_pivot.index)
        ax.set_xlim(years[0], years[-1])
        ax.xaxis.set_major_locator(MaxNLocator(integer=True, nbins=min(len(years), 20)))

        # Ensure y-axis starts at 0
        self._ensure_y_axis_starts_at_zero(ax)

        fig.tight_layout()

        # Export CSV if requested
        filename = "iron_ore_by_quality_over_time.png"
        if export_csv:
            self._save_chart_data_to_csv(df_pivot, filename)

        return self._save_figure(fig, filename)

    def plot_metallic_charges(
        self,
        trace_metallic_charges: dict[int, dict[str, float]],
        export_csv: bool = True,
    ) -> Optional[Path]:
        """Plot metallic charge consumption over time as a stacked area chart.

        Args:
            trace_metallic_charges: Nested dict {year: {charge_type: total_consumption_tonnes}}
            export_csv: If True, also export chart data to CSV (default: True)

        Returns:
            Path to saved plot, or None if no data to plot
        """
        if not trace_metallic_charges:
            self.logger.warning("No metallic charge data to plot")
            return None

        # Convert to DataFrame
        data_rows = []
        for year, charges in trace_metallic_charges.items():
            for charge_type, consumption in charges.items():
                data_rows.append({"year": year, "charge_type": charge_type, "consumption": consumption})

        if not data_rows:
            return None

        df = pd.DataFrame(data_rows)
        df["consumption_mt"] = df["consumption"] / 1e6

        # Exclude io_* charges — shown separately in the iron ore consumption chart
        df = df[~df["charge_type"].str.lower().str.startswith("io_")]

        if df.empty:
            self.logger.warning("No metallic charge data to plot after excluding iron ore")
            return None

        # Pivot
        df_pivot = df.pivot(index="year", columns="charge_type", values="consumption_mt")
        df_pivot = df_pivot.fillna(0)

        # Assign colors using centralized color mapping
        colors_for_plot = [self._get_metallic_charge_color(charge) for charge in df_pivot.columns]

        # Create plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        df_pivot.plot.area(
            ax=ax,
            color=colors_for_plot,
            alpha=0.8,
            linewidth=0,
        )

        # Formatting
        ax.set_title("Metallic Charge Consumption Over Time", fontsize=14, fontweight="bold")
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel("Total Consumption (Mt)", fontsize=12)
        legend_charges = self._legend_order_for_stack(df_pivot)
        charge_handles = [
            Patch(facecolor=self._get_metallic_charge_color(charge), label=charge) for charge in legend_charges
        ]
        self._style_legend(ax, title="Charge Type", handles=charge_handles, labels=legend_charges)
        ax.grid(axis="y", alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # X-axis formatting
        years = sorted(df_pivot.index)
        ax.set_xlim(years[0], years[-1])
        ax.xaxis.set_major_locator(MaxNLocator(integer=True, nbins=min(len(years), 20)))

        # Ensure y-axis starts at 0
        self._ensure_y_axis_starts_at_zero(ax)

        fig.tight_layout()

        # Export CSV if requested
        filename = "metallic_charges_over_time.png"
        if export_csv:
            self._save_chart_data_to_csv(df_pivot, filename)

        return self._save_figure(fig, filename)

    def plot_international_iron_trade(
        self,
        trace_international_iron_trade: dict[int, dict[str, float]],
        export_csv: bool = True,
    ) -> Optional[Path]:
        """Plot international iron product trade volumes over time as a stacked area chart (wedge chart).

        Args:
            trace_international_iron_trade: Nested dict {year: {iron_product: total_trade_volume_tonnes}}
            export_csv: If True, also export chart data to CSV (default: True)

        Returns:
            Path to saved plot, or None if no data to plot
        """
        if not trace_international_iron_trade:
            self.logger.warning("No international iron trade data to plot")
            return None

        # Convert to DataFrame
        data_rows = []
        for year, products in trace_international_iron_trade.items():
            for product, volume in products.items():
                data_rows.append({"year": year, "product": product, "volume": volume})

        if not data_rows:
            return None

        df = pd.DataFrame(data_rows)
        df["volume_mt"] = df["volume"] / 1e6

        # Pivot
        df_pivot = df.pivot(index="year", columns="product", values="volume_mt")
        df_pivot = df_pivot.fillna(0)

        # Define color scheme for iron products
        iron_product_colors = {
            "iron": "#8B4513",  # saddle brown - generic iron
            "hot_metal": "#DC143C",  # crimson - hot/molten
            "pig_iron": "#696969",  # dim gray - intermediate product
            "dri_low": "#87CEEB",  # sky blue (light) - low grade DRI
            "dri_mid": "#4682B4",  # steel blue (medium) - mid grade DRI
            "dri_high": "#000080",  # navy (dark) - high grade DRI
            "hbi_low": "#FFB6C1",  # light pink (light) - low grade HBI
            "hbi_mid": "#FF69B4",  # hot pink (medium) - mid grade HBI
            "hbi_high": "#C71585",  # medium violet red (dark) - high grade HBI
        }

        # Assign colors
        colors_for_plot = [iron_product_colors.get(product, "#808080") for product in df_pivot.columns]

        # Create plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        df_pivot.plot.area(
            ax=ax,
            color=colors_for_plot,
            alpha=0.8,
            linewidth=0,
        )

        # Formatting
        ax.set_title("International Iron Product Trade Volumes Over Time", fontsize=14, fontweight="bold")
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel("Total Trade Volume (Mt)", fontsize=12)
        legend_products = self._legend_order_for_stack(df_pivot)
        product_handles = [
            Patch(facecolor=iron_product_colors.get(product, "#808080"), label=product) for product in legend_products
        ]
        self._style_legend(ax, title="Iron Product", handles=product_handles, labels=legend_products)
        ax.grid(axis="y", alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # X-axis formatting
        years = sorted(df_pivot.index)
        ax.set_xlim(years[0], years[-1])
        ax.xaxis.set_major_locator(MaxNLocator(integer=True, nbins=min(len(years), 20)))

        # Ensure y-axis starts at 0
        self._ensure_y_axis_starts_at_zero(ax)

        fig.tight_layout()

        # Export CSV if requested
        filename = "international_iron_trade_over_time.png"
        if export_csv:
            self._save_chart_data_to_csv(df_pivot, filename)

        return self._save_figure(fig, filename)

    def plot_steel_cost_curve(
        self,
        curve: list[dict[str, float]],
        demand: float,
        filename: Optional[str] = None,
        export_csv: bool = True,
    ) -> Optional[Path]:
        """Plot a steel cost curve with marginal producer highlighted.

        Plots a steel cost curve (sorted by ascending cost) and indicates the
        marginal producer for a given demand level.

        Args:
            curve: List of dicts with 'cumulative_capacity' and 'production_cost'
            demand: Demanded capacity (will highlight intersection point)
            filename: Output filename for the plot
            export_csv: If True, also export chart data to CSV (default: True)

        Returns:
            Path to saved plot, or None if no data
        """
        if not curve:
            self.logger.warning("No cost curve data to plot")
            return None

        if filename is None:
            filename = f"{self.COST_CURVES_SUBDIR}/cost_curve_steel.png"

        # Extract x (cumulative capacities) and y (production costs) from the curve
        cumulative_capacities = [point["cumulative_capacity"] for point in curve]
        production_costs = [point["production_cost"] for point in curve]

        # Convert capacities from t to kt
        cumulative_capacities = [x / 1000 for x in cumulative_capacities]
        demand_kt = demand / 1000

        # Find maximum capacity to check demand boundaries
        max_capacity = cumulative_capacities[-1] if curve else 0

        # If demand is out of range, clip or note it
        if demand_kt < 0:
            demand_kt = 0
        elif demand_kt > max_capacity:
            self.logger.warning(
                f"Demand ({demand_kt}) exceeds total available capacity ({max_capacity}). "
                "Marginal producer cost will be that of the final producer."
            )
            demand_kt = max_capacity

        # Find the marginal producer
        marginal_producer = None
        for point in curve:
            if point["cumulative_capacity"] / 1000 >= demand_kt:
                marginal_producer = point
                break

        # Create plot
        fig, ax = plt.subplots(figsize=(10, 6))

        # Plot cost curve as step plot
        ax.step(cumulative_capacities, production_costs, where="post", label="Cost Curve", linewidth=2)

        # Plot vertical line at demand level
        ax.axvline(x=demand_kt, color="red", linestyle="--", label="Demand", linewidth=1.5)

        # If we found a valid marginal producer, annotate it
        if marginal_producer:
            marginal_x = demand_kt
            marginal_cost = marginal_producer["production_cost"]

            # Horizontal line at the marginal cost
            ax.axhline(y=marginal_cost, color="gray", linestyle="--", linewidth=1)

            # Mark the intersection
            ax.scatter(marginal_x, marginal_cost, color="red", zorder=5, s=100)

            # Add text annotation
            ax.text(
                marginal_x,
                marginal_cost,
                f"  Marginal producer cost = ${marginal_cost:.2f}/t",
                color="red",
                verticalalignment="bottom",
                fontsize=10,
            )

        # Styling
        ax.set_title("Steel Cost Curve", fontsize=14, fontweight="bold")
        ax.set_xlabel("Cumulative Capacity (kt)", fontsize=12)
        ax.set_ylabel("Production Cost (US$/t)", fontsize=12)
        self._style_legend(ax)
        ax.grid(True, alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # Ensure y-axis starts at 0
        self._ensure_y_axis_starts_at_zero(ax)

        fig.tight_layout()

        # Export CSV if requested
        if export_csv:
            # Convert curve data to DataFrame
            df_curve = pd.DataFrame(curve)
            df_curve["cumulative_capacity_kt"] = df_curve["cumulative_capacity"] / 1000
            df_curve = df_curve[["cumulative_capacity_kt", "production_cost"]]
            df_curve.index.name = "step"
            self._save_chart_data_to_csv(df_curve, filename, subdir="plots_dir")

        return self._save_figure(fig, filename, subdir="plots_dir")

    def plot_cost_curve_per_region(
        self,
        plants: "PlantRepository",
        filename: Optional[str] = None,
        export_csv: bool = True,
    ) -> Optional[Path]:
        """Plot cost curve with regions colored separately.

        Args:
            plants: PlantRepository containing plant data
            filename: Output filename for the plot
            export_csv: If True, also export chart data to CSV (default: True)

        Returns:
            Path to saved plot, or None if no data
        """
        if filename is None:
            filename = f"{self.COST_CURVES_SUBDIR}/cost_curve_per_region.png"

        # Initialize variables for plotting
        current_capacity = 0
        regional_data: dict = {}

        # Collect data for rectangle plotting
        for plant in plants.list():
            if not hasattr(plant, "average_steel_cost") or not hasattr(plant, "steel_capacity"):
                continue
            region = plant.location.region
            regional_data[region] = regional_data.get(region, []) + [
                (
                    (float(plant.steel_capacity) if plant.steel_capacity is not None else 0.0)
                    * (float(plant.average_steel_cost) if plant.average_steel_cost is not None else 0.0),
                    float(plant.steel_capacity) if plant.steel_capacity is not None else 0.0,
                )
            ]

        if not regional_data:
            self.logger.warning("No plant data to plot cost curve per region")
            return None

        # Prepare sorted rectangles
        sorted_rectangles = []
        region_colors: dict[str, Any] = {}

        # Use configured region colors if available, otherwise generate colors
        if self.config.region_colors:
            region_colors = self.config.region_colors.copy()

        # Generate colors for regions not in config
        color_palette = plt.cm.get_cmap("tab20", len(regional_data))
        for idx, region in enumerate(regional_data.keys()):
            if region not in region_colors:
                region_colors[region] = color_palette(idx)

        current_capacity = 0
        for region, data in regional_data.items():
            total_cost = sum([x[0] for x in data])
            total_capacity = sum([x[1] for x in data])
            if total_capacity > 0:
                width = total_capacity * T_TO_MT  # Convert to megatons
                height = total_cost / total_capacity
                sorted_rectangles.append((current_capacity, height, width, region))
                current_capacity += width

        # Sort rectangles by height (average cost) in ascending order
        sorted_rectangles.sort(key=lambda x: x[1])

        # Reset current capacity for sorted rectangles
        current_capacity = 0
        final_rectangles = []
        for x_start, height, width, region in sorted_rectangles:
            final_rectangles.append((current_capacity, height, width, region))
            current_capacity += width

        # Create plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        for x_start, height, width, region in final_rectangles:
            ax.bar(
                x_start,
                height,
                width=width,
                align="edge",
                edgecolor="black",
                color=region_colors[region],
                label=region,
            )

        # Add legend (remove duplicates)
        handles, labels = ax.get_legend_handles_labels()
        by_label = dict(zip(labels, handles))
        self._style_legend(ax, title="Region", handles=list(by_label.values()), labels=list(by_label.keys()))

        # Styling
        ax.set_xlabel("Cumulative Annual Capacity (Mt/year)", fontsize=12)
        ax.set_ylabel("Cost per Unit (US$/t)", fontsize=12)
        ax.set_title("Cost Curve per Region", fontsize=14, fontweight="bold")
        ax.grid(True, linestyle="--", alpha=self.config.grid_alpha)

        # Ensure y-axis starts at 0
        self._ensure_y_axis_starts_at_zero(ax)

        fig.tight_layout()

        # Export CSV if requested
        if export_csv:
            # Convert rectangles to DataFrame
            df_regions = pd.DataFrame(
                final_rectangles, columns=["cumulative_capacity_start_mt", "cost_per_unit_usd_t", "width_mt", "region"]
            )
            df_regions["cumulative_capacity_end_mt"] = (
                df_regions["cumulative_capacity_start_mt"] + df_regions["width_mt"]
            )
            df_regions = df_regions[
                [
                    "region",
                    "cumulative_capacity_start_mt",
                    "cumulative_capacity_end_mt",
                    "width_mt",
                    "cost_per_unit_usd_t",
                ]
            ]
            df_regions.index.name = "segment"
            self._save_chart_data_to_csv(df_regions, filename, subdir="plots_dir")

        return self._save_figure(fig, filename, subdir="plots_dir")

    def plot_cost_curve_for_commodity(
        self,
        cost_curve: list[dict],
        total_demand: float,
        filename: Optional[str] = None,
        export_csv: bool = True,
    ) -> Optional[Path]:
        """Plot cost curve for a commodity with demand line.

        Args:
            cost_curve: List of dicts with 'cumulative_capacity' and 'production_cost'
            total_demand: Total demand to highlight on the curve
            filename: Output filename for the plot
            export_csv: If True, also export chart data to CSV (default: True)

        Returns:
            Path to saved plot, or None if no data
        """
        if not cost_curve:
            self.logger.warning("No cost curve data to plot for commodity")
            return None

        if filename is None:
            filename = f"{self.COST_CURVES_SUBDIR}/cost_curve.png"

        # Prepare x and y data for plotting
        x_vals = []
        y_vals = []

        for point in cost_curve:
            # Handle cumulative_capacity that may be a Volumes object
            try:
                cap = float(point["cumulative_capacity"])
            except (TypeError, ValueError):
                cap = (
                    point["cumulative_capacity"].value
                    if hasattr(point["cumulative_capacity"], "value")
                    else point["cumulative_capacity"]
                )

            x_vals.append(cap)
            y_vals.append(point["production_cost"])

        # Create the plot
        fig, ax = plt.subplots(figsize=(10, 6))
        ax.step(x_vals, y_vals, where="post", label="Cost Curve", linewidth=2)

        # Add demand line
        ax.axvline(x=total_demand, color="red", linestyle="--", label="Total Demand", linewidth=1.5)

        # Styling
        ax.set_xlabel("Cumulative Capacity", fontsize=12)
        ax.set_ylabel("Production Cost", fontsize=12)
        ax.set_title("Cost Curve", fontsize=14, fontweight="bold")
        self._style_legend(ax)
        ax.grid(True, alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # Ensure y-axis starts at 0
        self._ensure_y_axis_starts_at_zero(ax)

        fig.tight_layout()

        # Export CSV if requested
        if export_csv:
            # Convert cost curve data to DataFrame
            df_curve = pd.DataFrame({"cumulative_capacity": x_vals, "production_cost": y_vals})
            df_curve.index.name = "step"
            self._save_chart_data_to_csv(df_curve, filename, subdir="plots_dir")

        return self._save_figure(fig, filename, subdir="plots_dir")

    def plot_cost_curve_with_breakdown(
        self,
        data_file: pd.DataFrame,
        product_type: str,
        year: int,
        show_breakdown: bool = True,
        filename: Optional[str] = None,
        export_csv: bool = True,
    ) -> Optional[Path]:
        """Plot cost curve with stacked bar breakdown showing cost components per furnace group.

        Args:
            data_file: DataFrame with furnace group data
            product_type: Type of product ('steel' or 'iron')
            year: Year to plot
            show_breakdown: If True, show cost breakdown as stacked bars
            filename: Optional custom filename (default: auto-generated from product/year)
            export_csv: If True, also export chart data to CSV (default: True)

        Returns:
            Path to saved plot, or None if no data
        """
        df = data_file.groupby(["furnace_group_id", "year"], as_index=False).first().set_index(["product", "year"])

        # Check if the requested year exists in the data
        available_years = df.index.get_level_values("year").unique()
        if year not in available_years:
            self.logger.warning(f"Year {year} not found in data. Available years: {sorted(available_years)}")
            # Use the closest available year
            year = max([y for y in available_years if y <= year] or [min(available_years)])
            self.logger.info(f"Using year {year} instead for cost curve plot")

        # Check if product_type exists
        if product_type not in df.index.get_level_values("product"):
            self.logger.warning(f"Product type '{product_type}' not found in data. Skipping cost curve plot.")
            return None

        # Sort the index to avoid performance warning
        df = df.sort_index()

        # Get the data for the specific product and year
        demand = cast(pd.DataFrame, df.loc[product_type]).loc[year].production.sum()

        # Prepare cost breakdown components
        component_columns = []

        if show_breakdown:
            # Extract cost components from the data
            self.logger.debug(f"Available columns in df: {list(df.columns)}")
            if "cost_breakdown" in df.columns:
                # If we have the cost_breakdown dictionary column (nested by feedstock)
                cost_df = cast(pd.DataFrame, df.loc[(product_type, year)]).copy()

                # Parse and flatten the cost_breakdown structure
                for idx, row in cost_df.iterrows():
                    if pd.notna(row.get("cost_breakdown")) and isinstance(row["cost_breakdown"], dict):
                        # Aggregate costs across all feedstocks
                        aggregated_costs = {}

                        for feedstock, costs in row["cost_breakdown"].items():
                            if isinstance(costs, dict):
                                for cost_type, value in costs.items():
                                    if cost_type == "total_cost":
                                        if "material_cost" not in aggregated_costs:
                                            aggregated_costs["material_cost"] = 0
                                        aggregated_costs["material_cost"] += value
                                    elif cost_type not in ["demand", "unit_cost"]:
                                        if cost_type not in aggregated_costs:
                                            aggregated_costs[cost_type] = 0
                                        aggregated_costs[cost_type] += value

                        # Add the aggregated costs as columns to the dataframe
                        for cost_type, value in aggregated_costs.items():
                            cost_df.at[idx, cost_type] = value  # type: ignore[index]

                # Now identify component columns from the flattened data
                if "material_cost" in cost_df.columns:
                    component_columns.append("material_cost")

                # Handle columns with spaces in names
                for col in ["fixed opex", "carbon cost", "debt share"]:
                    if col in cost_df.columns:
                        new_col = col.replace(" ", "_")
                        cost_df[new_col] = cost_df[col]
                        component_columns.append(new_col)

                # Energy columns
                energy_cols = [
                    col
                    for col in cost_df.columns
                    if col in ["electricity", "coal", "natural gas", "natural_gas", "bf gas", "bof gas", "cog", "steam"]
                ]
                for col in energy_cols:
                    if pd.api.types.is_numeric_dtype(cost_df[col]):
                        component_columns.append(col)
            else:
                # Build cost breakdown from available columns
                cost_df = cast(pd.DataFrame, df.loc[(product_type, year)]).copy()

                # Add cost breakdown columns that start with "cost_breakdown - "
                breakdown_cols = [col for col in cost_df.columns if col.startswith("cost_breakdown - ")]
                breakdown_names = set()

                for col in breakdown_cols:
                    clean_name = col.replace("cost_breakdown - ", "").strip()
                    cost_df[clean_name] = cost_df[col]
                    component_columns.append(clean_name)
                    breakdown_names.add(clean_name)

                # Material costs - only add if not already covered by cost breakdown
                if "material_cost" not in breakdown_names:
                    if "material_unit_cost" in cost_df.columns:
                        cost_df["material_cost"] = cost_df["material_unit_cost"]
                        component_columns.append("material_cost")
                    elif "material_cost" in cost_df.columns:
                        component_columns.append("material_cost")
                    elif "material cost" in cost_df.columns:
                        cost_df["material_cost"] = cost_df["material cost"]
                        component_columns.append("material_cost")

                # Fixed OPEX - only add if not already covered by cost breakdown
                if "unit_fopex" in cost_df.columns and "unit fopex" not in breakdown_names:
                    component_columns.append("unit_fopex")

                # Carbon cost - only add if not already covered by cost breakdown
                if "carbon_cost" in cost_df.columns and "carbon cost" not in breakdown_names:
                    component_columns.append("carbon_cost")
                elif "carbon_cost_per_unit" in cost_df.columns and "carbon cost" not in breakdown_names:
                    if "production" in cost_df.columns:
                        cost_df["carbon_cost"] = cost_df["carbon_cost_per_unit"] * cost_df["production"]
                        component_columns.append("carbon_cost")

                # Debt service - only add if not already covered by cost breakdown
                if "debt_share" in cost_df.columns and "debt share" not in breakdown_names:
                    component_columns.append("debt_share")

                # Calculate total production cost as sum of components
                if component_columns:
                    cost_df["production_cost"] = cost_df[component_columns].sum(axis=1, skipna=True)
                else:
                    cost_df["production_cost"] = df["unit_production_cost"]
        else:
            # Original simple calculation
            df["production_cost"] = df["unit_production_cost"]
            cost_df = cast(pd.DataFrame, df.loc[(product_type, year)])[["production_cost", "region", "capacity"]].copy()

        # Sort by production cost
        cost_df = cost_df.sort_values("production_cost")

        # Check if we have valid data
        if cost_df.empty:
            self.logger.warning(f"No data for {product_type} in year {year}. Skipping cost curve plot.")
            return None

        if cost_df["production_cost"].isna().all():
            self.logger.warning(f"All production costs are NaN for {product_type} in year {year}.")
            return None

        # Remove rows with NaN production costs
        cost_df = cost_df.dropna(subset=["production_cost"])
        if cost_df.empty:
            self.logger.warning(f"No valid production costs for {product_type} in year {year}.")
            return None

        cost_df["clearing_capacity"] = cost_df["capacity"].cumsum()

        # Create the plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)
        cum_x = 0.0

        if show_breakdown and component_columns:
            # Define colors for each cost component
            component_colors: dict[str, Any] = {
                "material_cost": "#8B4513",  # Saddle brown
                "electricity": "#FFD700",  # Gold
                "coal": "#2F4F4F",  # Dark slate gray
                "natural_gas": "#87CEEB",  # Sky blue
                "bf gas": "#4682B4",  # Steel blue
                "bof gas": "#5F9EA0",  # Cadet blue
                "cog": "#696969",  # Dim gray
                "steam": "#FFA500",  # Orange
                "unit_fopex": "#708090",  # Slate gray
                "unit fopex": "#708090",  # Slate gray (space version)
                "carbon_cost": "#DC143C",  # Crimson
                "carbon cost": "#DC143C",  # Crimson (space version)
                "debt_share": "#4B0082",  # Indigo
                "debt share": "#4B0082",  # Indigo (space version)
            }

            # Plot stacked bars for each furnace group
            for _, row in cost_df.iterrows():
                cap = row["capacity"]
                x0 = cum_x
                x1 = cum_x + cap

                # Stack the cost components
                y_bottom = 0
                for component in component_columns:
                    if component in row and pd.notna(row[component]) and row[component] > 0:
                        component_value = row[component]

                        # Get color for this component
                        if component in component_colors:
                            color = component_colors[component]
                        else:
                            color = cm.get_cmap("Set3")(hash(component) % 12 / 12)
                            component_colors[component] = color

                        # Draw the stacked segment
                        ax.fill_between(
                            [x0, x1],
                            [y_bottom, y_bottom],
                            [y_bottom + component_value, y_bottom + component_value],
                            color=color,
                            alpha=0.8,
                            linewidth=0.5,
                            edgecolor="black",
                            label=component if cum_x == 0 else "",  # Only label once
                        )

                        y_bottom += component_value

                # Add region border/outline
                rectangle = plt.Rectangle(
                    (x0, 0),
                    cap,
                    row["production_cost"],
                    fill=False,
                    edgecolor="black",
                    linewidth=2,
                    linestyle="-",
                )
                ax.add_patch(rectangle)

                cum_x = x1
        else:
            # Original simple filled rectangles (fallback)
            for _, row in cost_df.iterrows():
                cost = row["production_cost"]
                cap = row["capacity"]
                color = "steelblue"

                x0 = cum_x
                x1 = cum_x + cap

                ax.fill_between([x0, x1], [cost, cost], [0, 0], color=color, step="pre", linewidth=0)
                ax.hlines(y=cost, xmin=x0, xmax=x1, colors="black", linewidth=0.8, zorder=2)

                cum_x = x1

        # Add market clearing price and demand lines
        clearing_cost = (
            cost_df[cost_df["clearing_capacity"] <= demand].iloc[-1].production_cost if not cost_df.empty else 0
        )

        ax.axhline(y=clearing_cost, color="r", linestyle="--", linewidth=1.5, label="Market clearing price")
        ax.axvline(x=demand, color="r", linestyle="--", linewidth=1.5, label="Demand")

        # Add clearing price annotation
        ax.text(
            x=cost_df.iloc[-1]["clearing_capacity"] * 0.7 if not cost_df.empty else 0,
            y=clearing_cost + 30,
            s=f"Market clearing price = {clearing_cost:.1f} $/t",
            ha="center",
            va="bottom",
            color="black",
            fontsize=10,
            backgroundcolor="white",
            alpha=0.8,
        )

        # Set title and labels
        breakdown_text = " with Cost Breakdown" if show_breakdown else ""
        ax.set_title(
            f"Cost Curve for {product_type.capitalize()} in {year}{breakdown_text}",
            fontsize=14,
            fontweight="bold",
        )
        ax.set_xlabel("Cumulative Capacity (kt)", fontsize=12)
        ax.set_ylabel("Production Cost ($/t)", fontsize=12)

        # Set axis limits
        if cum_x > 0:
            ax.set_xlim(0, cum_x * 1.02)
        else:
            ax.set_xlim(0, 1)

        max_cost = cost_df["production_cost"].max()
        if pd.isna(max_cost) or np.isinf(max_cost) or max_cost <= 0:
            self.logger.warning(f"Invalid max production cost: {max_cost}. Using default y-axis range.")
            ax.set_ylim(0, 1000)
        else:
            ax.set_ylim(0, max_cost * 1.1)

        # Create legend
        if show_breakdown and component_columns:
            handles, labels = ax.get_legend_handles_labels()
            if handles:
                ax.legend(
                    handles=handles[: len(component_columns)],
                    title="Cost Components",
                    loc="upper left",
                    frameon=True,
                    fontsize=9,
                )

        # Add grid
        ax.grid(True, alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # Ensure y-axis starts at 0
        self._ensure_y_axis_starts_at_zero(ax)

        fig.tight_layout()

        # Generate filename if not provided
        if filename is None:
            filename = (
                f"{product_type}_cost_curve_breakdown_{year}.png"
                if show_breakdown
                else f"{product_type}_cost_curve_{year}.png"
            )

        # Export CSV if requested
        if export_csv:
            # Prepare CSV export with relevant columns
            csv_columns = ["production_cost", "capacity", "region", "clearing_capacity"]
            if show_breakdown and component_columns:
                csv_columns.extend(component_columns)
            # Only include columns that actually exist in cost_df
            csv_columns = [col for col in csv_columns if col in cost_df.columns]
            df_export = cost_df[csv_columns].copy()
            self._save_chart_data_to_csv(df_export, filename)

        return self._save_figure(fig, filename)

    def plot_cost_curve_step(
        self,
        data_file: pd.DataFrame,
        product_type: str,
        product_demand: float,
        year: int,
        capacity_limit: float,
        units: str,
        clearing_share: float,
        price_buffer: float,
        aggregation: str = "region",
        filename: Optional[str] = None,
        export_csv: bool = True,
    ) -> Optional[Path]:
        """Plot a per-furnace stepped cost curve aggregated by region or technology.

        Args:
            data_file: Post-processed DataFrame with per-furnace rows for the simulation.
            product_type: 'steel' or 'iron'.
            product_demand: Tonnes demanded for the product/year (used to draw the demand line).
                If None or non-positive, falls back to the sum of `production` for the product/year.
            year: Year to plot. Falls back to the closest earlier available year if absent.
            capacity_limit: Multiplier applied to capacity in `_prepare_cost_curve_dataframe`.
            units: Unit string for the x-axis label (e.g. 'Mt', 'kt', 't').
            clearing_share: Fraction of cumulative capacity that participates in clearing
                (must match the engine value for the same product).
            price_buffer: USD/tonne shortage premium added when demand exceeds the dispatchable
                slice (must match the engine value for the same product).
            aggregation: 'region' or 'technology' — drives colour scheme and legend title.
            filename: Optional override; defaults to `cost_curves/cost_curve_{product_type}_by_{aggregation}_{year}.png`.
            export_csv: If True, also export the prepared cost-curve dataframe to CSV.

        Returns:
            Path to saved plot, or None if there is no data to plot.

        Notes:
            Y-axis is clipped to a 99.5th-percentile band (capped at $2000/t) to keep extreme
            outliers from compressing the visible range; the clearing-price line annotates
            "(clipped for scale)" if it falls beyond the visible y-limit.
        """
        demand = product_demand
        if (demand is None) or (isinstance(demand, (int, float, np.floating)) and demand <= 0):
            if "production" in data_file.columns:
                mask = (data_file["product"] == product_type) & (data_file["year"] == year)
                demand = float(data_file.loc[mask, "production"].sum())
            else:
                demand = 0.0

        if "year" in data_file.columns:
            available_years = sorted(set(int(y) for y in data_file["year"].dropna()))
            if year not in available_years and available_years:
                self.logger.warning(f"Year {year} not found in data. Available years: {available_years}")
                lower_years = [y for y in available_years if y <= year]
                year = max(lower_years) if lower_years else min(available_years)
                self.logger.info(f"Using year {year} instead for cost curve plot")

        if aggregation == "region":
            colour_scheme = self.config.region_colors
        elif aggregation == "technology":
            colour_scheme = self.config.tech_colors
        else:
            self.logger.warning(f"Unsupported aggregation '{aggregation}' for cost curve plot. Defaulting to 'region'.")
            aggregation = "region"
            colour_scheme = self.config.region_colors

        cost_df = _prepare_cost_curve_dataframe(
            data_frame=data_file,
            product_type=product_type,
            year=year,
            aggregation=aggregation,
            capacity_limit=capacity_limit,
        )

        if cost_df.empty:
            self.logger.warning(f"No data for {product_type} in year {year}. Skipping cost curve plot.")
            return None

        clearing_cost, demand_line_x, total_capacity = _compute_market_clearing(
            cost_df, demand, clearing_share, price_buffer
        )

        fig, ax = plt.subplots(figsize=(10, 6))
        cum_x = 0.0

        for _, row in cost_df.iterrows():
            cost = row["production_cost"]
            cap = row["capacity"]
            agg_object = row[aggregation]

            color = colour_scheme.get(agg_object, "#8c8c8c")

            x0 = cum_x
            x1 = cum_x + cap

            ax.fill_between(
                [x0, x1],
                [cost, cost],
                [0, 0],
                color=color,
                step="pre",
                linewidth=0,
            )

            ax.hlines(y=cost, xmin=x0, xmax=x1, colors="black", linewidth=0.4, zorder=2)

            cum_x = x1

        costs = cost_df["production_cost"].values
        cum_caps = cost_df["clearing_capacity"].values
        for i in range(len(cost_df) - 1):
            boundary_x = cum_caps[i]
            y0 = costs[i]
            y1 = costs[i + 1]
            ax.vlines(x=boundary_x, ymin=y0, ymax=y1, colors="gray", linewidth=0.6, linestyle="--", zorder=1)

        legend_handles = [
            Patch(color=color, label=agg) for agg, color in colour_scheme.items() if agg in cost_df[aggregation].values
        ]
        first_legend = self._style_legend(
            ax,
            title=aggregation.capitalize(),
            handles=legend_handles,
            labels=[h.get_label() for h in legend_handles],
        )

        annotation_text = f"Market clearing price = {clearing_cost:.1f} $/t"
        share_pct = int(round(clearing_share * 100))
        if demand > total_capacity:
            annotation_text += f"\n(Demand exceeds total supply: boundary cost + ${int(price_buffer)} shortage premium)"
        elif demand_line_x > clearing_share * total_capacity:
            annotation_text += (
                f"\n(Demand exceeds dispatchable {share_pct}%: boundary cost + ${int(price_buffer)} shortage premium)"
            )

        ax.set_title(f"Cost curve for {product_type} in {year}", fontsize=14, fontweight="bold")

        if cum_x > 0:
            if demand > total_capacity:
                x_padding = max(total_capacity * 0.02, 1e-6)
                ax.set_xlim(0, total_capacity + x_padding)
            else:
                ax.set_xlim(0, total_capacity)
        else:
            ax.set_xlim(0, 1)

        max_cost = cost_df["production_cost"].max()
        if pd.isna(max_cost) or np.isinf(max_cost) or max_cost <= 0:
            self.logger.warning(f"Invalid max production cost: {max_cost}. Using default y-axis range.")
            ax.set_ylim(0, 1000)
        else:
            outlier_cap = 2000.0
            if max_cost > outlier_cap:
                y_limit = outlier_cap
            else:
                upper_percentile = cost_df["production_cost"].quantile(0.995)
                if pd.notna(upper_percentile) and upper_percentile > 0 and max_cost > upper_percentile * 1.5:
                    y_limit = upper_percentile * 1.1
                else:
                    y_limit = max_cost * 1.1
            ax.set_ylim(0, y_limit)

        ax.set_xlabel(f"Cumulative Capacity [{units}]", fontsize=12)
        ax.set_ylabel("Production Cost ($/t)", fontsize=12)
        ax.grid(True, alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        display_clearing_cost = min(clearing_cost, ax.get_ylim()[1])
        ax.axhline(y=display_clearing_cost, color="r", linestyle="--", linewidth=1.2, zorder=7, clip_on=False)
        ax.axvline(x=demand_line_x, color="green", linestyle="--", linewidth=1.2, zorder=7, clip_on=False)
        share_marker_drawn = clearing_share < 1.0 and total_capacity > 0
        if share_marker_drawn:
            marker_x = clearing_share * total_capacity
            ax.axvline(x=marker_x, color="dimgray", linestyle="--", linewidth=1.2, zorder=6)
        if display_clearing_cost < clearing_cost:
            annotation_text += "\n(clipped for scale)"

        ref_handles = [
            Line2D([0], [0], color="r", linestyle="--", linewidth=1.5, label="Market clearing price"),
            Line2D([0], [0], color="green", linestyle="--", linewidth=1.5, label="Demand"),
        ]
        if share_marker_drawn:
            ref_handles.append(
                Line2D(
                    [0],
                    [0],
                    color="dimgray",
                    linestyle="--",
                    linewidth=1.5,
                    label=f"Market clearing share ({share_pct}%)",
                ),
            )
        if first_legend is not None:
            ax.add_artist(first_legend)
        ref_legend = ax.legend(
            handles=ref_handles,
            title="Reference lines",
            bbox_to_anchor=(1.05, 0.0),
            loc="lower left",
            frameon=self.config.legend_frameon,
            fontsize=self.config.legend_fontsize,
        )
        if ref_legend:
            ref_legend.get_title().set_fontweight("bold")

        ax.text(
            0.02,
            0.98,
            annotation_text,
            transform=ax.transAxes,
            ha="left",
            va="top",
            color="black",
            fontsize=11,
            bbox=dict(boxstyle="round,pad=0.4", fc="white", ec="gray", alpha=0.85),
            zorder=6,
        )

        if filename is None:
            filename = f"{self.COST_CURVES_SUBDIR}/cost_curve_{product_type}_by_{aggregation}_{year}.png"

        if export_csv:
            self._save_chart_data_to_csv(cost_df, filename, subdir="plots_dir")

        return self._save_figure(fig, filename, subdir="plots_dir")

    def plot_market_prices(
        self,
        price_df: pd.DataFrame,
        start_year: int,
        end_year: int,
        export_csv: bool = True,
    ) -> Optional[Path]:
        """Plot market prices over time as a line chart.

        Renders steel, scrap, and iron weighted-average cost lines (whichever columns are
        present) using the standard SteelPlotter styling: side legend, dashed gridlines, and
        the bottom-right Steel-IQ footer applied via ``_save_figure``.

        Args:
            price_df: DataFrame with a ``year`` column and any of:
                ``steel_price_usd_per_t``, ``scrap_price_usd_per_t``,
                ``iron_weighted_avg_cost_usd_per_t``.
            start_year: First year in the price series; used in the output filename.
            end_year: Last year in the price series; used in the output filename.
            export_csv: If True, also export the price data to CSV alongside the PNG.

        Returns:
            Path to the saved plot, or None if there is no data to plot.
        """
        if price_df.empty or "year" not in price_df.columns:
            self.logger.warning("No market price data to plot")
            return None

        series_specs = [
            ("steel_price_usd_per_t", "Steel", "o", "#1f77b4", 1.0),
            ("scrap_price_usd_per_t", "Scrap", "^", "#2ca02c", 1.0),
            ("iron_weighted_avg_cost_usd_per_t", "Iron (weighted avg cost)", "D", "#ff7f0e", 0.6),
        ]

        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)
        plotted_any = False
        for column, label, marker, color, alpha in series_specs:
            if column not in price_df.columns:
                continue
            ax.plot(
                price_df["year"],
                price_df[column],
                marker=marker,
                linewidth=2,
                label=label,
                color=color,
                alpha=alpha,
            )
            plotted_any = True

        if not plotted_any:
            self.logger.warning("No recognised market price columns to plot")
            plt.close(fig)
            return None

        ax.set_title("Market Prices - Steel, Iron and Scrap", fontsize=14, fontweight="bold")
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel("Price / Cost (USD/t)", fontsize=12)
        ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _p: f"${x:,.0f}"))
        ax.set_ylim(bottom=0)
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))
        ax.grid(True, alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        self._style_legend(ax, title="Series")

        filename = f"market_prices_{start_year}_{end_year}.png"
        if export_csv:
            self._save_chart_data_to_csv(price_df, filename, subdir="pam_plots_dir")

        return self._save_figure(fig, filename, subdir="pam_plots_dir")

    # Original grouped-bar version — superseded by the stacked variant below. Kept commented for revert.
    # def plot_capacity_development_by_technology(
    #     self,
    #     data_file: pd.DataFrame,
    #     units: str = "Mt",
    #     filename: str = "Capacity_development_by_technology.png",
    #     export_csv: bool = True,
    # ) -> Optional[Path]:
    #     """Plot year-on-year capacity development by technology.
    #
    #     Shows the change in capacity for each technology from year to year as a grouped bar chart.
    #     """
    #     required_cols = ["furnace_group_id", "year", "technology", "capacity", "product"]
    #     missing_cols = [col for col in required_cols if col not in data_file.columns]
    #     if missing_cols:
    #         raise ValueError(f"DataFrame missing required columns: {missing_cols}")
    #
    #     data_file = data_file.copy()
    #
    #     unique_techs = data_file["technology"].unique()
    #     tech_colors = {}
    #     for tech in unique_techs:
    #         tech_colors[tech] = self._ensure_tech_color(tech)
    #
    #     by_technology = (
    #         data_file.drop_duplicates(subset=["furnace_group_id", "year"])
    #         .groupby(["year", "technology"])["capacity"]
    #         .sum()
    #         .unstack("technology")
    #     )
    #     by_technology = by_technology.fillna(0)
    #     capacity_diff = by_technology.diff()
    #
    #     fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)
    #     capacity_diff.plot(
    #         ax=ax,
    #         kind="bar",
    #         stacked=False,
    #         ylabel=f"Capacity [{units}]",
    #         xlabel="Year",
    #         legend=True,
    #         color=tech_colors,
    #     )
    #
    #     ax.set_title("Year-on-Year Capacity Development by Technology", fontsize=14, fontweight="bold")
    #     self._style_legend(ax, title="Technology")
    #     ax.grid(axis="y", alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)
    #     ax.tick_params(axis="x", rotation=45)
    #     self._ensure_y_axis_starts_at_zero(ax)
    #     fig.tight_layout()
    #
    #     if export_csv:
    #         self._save_chart_data_to_csv(capacity_diff, filename)
    #
    #     return self._save_figure(fig, filename)

    def plot_capacity_development_by_technology(
        self,
        data_file: pd.DataFrame,
        product_type: str = "steel",
        units: str = "Mt",
        filename: Optional[str] = None,
        export_csv: bool = True,
    ) -> Optional[Path]:
        """Plot year-on-year capacity change by technology, split by sign.

        Additions stack upward and retirements stack downward around a y=0 line, so
        the net change per year and the technology mix on each side are both readable
        at a glance. Filtered to a single product so iron and steel fleets are charted
        separately.

        Args:
            data_file: DataFrame with columns: furnace_group_id, year, technology, capacity, product
            product_type: Product to filter on, e.g. "steel" or "iron" (default: "steel")
            units: Unit string for y-axis label (e.g., "Mt", "ktpa")
            filename: Output filename. If None, derived from product_type.
            export_csv: If True, also export chart data to CSV (default: True)

        Returns:
            Path to saved plot, or None if no data
        """
        required_cols = ["furnace_group_id", "year", "technology", "capacity", "product"]
        missing_cols = [col for col in required_cols if col not in data_file.columns]
        if missing_cols:
            raise ValueError(f"DataFrame missing required columns: {missing_cols}")

        data_file = data_file.copy()
        data_file = data_file[data_file["product"] == product_type]

        if data_file.empty:
            self.logger.warning(f"No data for product type '{product_type}' to plot")
            return None

        if filename is None:
            filename = f"Capacity_development_by_technology_{product_type}.png"

        for tech in data_file["technology"].unique():
            self._ensure_tech_color(tech)

        by_technology = (
            data_file.drop_duplicates(subset=["furnace_group_id", "year"])
            .groupby(["year", "technology"])["capacity"]
            .sum()
            .unstack("technology")
            .fillna(0)
        )
        capacity_diff = by_technology.diff().dropna(how="all")

        if capacity_diff.empty:
            return None

        positives = capacity_diff.clip(lower=0)
        negatives = capacity_diff.clip(upper=0)
        colours = [self.config.tech_colors.get(tech, "brown") for tech in capacity_diff.columns]

        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)
        positives.plot(ax=ax, kind="bar", stacked=True, color=colours, width=0.8, legend=False)
        negatives.plot(ax=ax, kind="bar", stacked=True, color=colours, width=0.8, legend=False)

        ax.axhline(0, color="black", linewidth=0.8)
        ax.set_title(
            f"Year-on-Year Capacity Development by Technology — {product_type.title()}",
            fontsize=14,
            fontweight="bold",
        )
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel(f"Capacity change [{units}]", fontsize=12)

        legend_techs = self._legend_order_for_stack(capacity_diff)
        tech_handles = [
            Patch(facecolor=self.config.tech_colors.get(tech, "brown"), label=tech) for tech in legend_techs
        ]
        self._style_legend(ax, title="Technology", handles=tech_handles, labels=legend_techs)
        ax.grid(axis="y", alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)
        ax.tick_params(axis="x", rotation=45)

        fig.tight_layout()

        if export_csv:
            self._save_chart_data_to_csv(capacity_diff, filename)

        return self._save_figure(fig, filename)

    def plot_area_chart_by_region_or_technology(
        self,
        dataframe: pd.DataFrame,
        column_name: str,
        title: str,
        units: str,
        pivot_columns: list[str],
        product_type: str = "steel",
        filename: Optional[str] = None,
        export_csv: bool = True,
    ) -> Optional[Path]:
        """Plot a stacked area chart of a column grouped by region or technology.

        This is a general-purpose method for creating stacked area charts showing
        how capacity, production, or other metrics change over time, broken down
        by region or technology.

        Args:
            dataframe: DataFrame with columns: furnace_group_id, year, product, region/technology
            column_name: Column to plot (e.g., "capacity", "production")
            title: Plot title
            units: Unit string for y-axis label (e.g., "Mtpa", "ktpa")
            pivot_columns: List of columns to pivot by (e.g., ["region"] or ["technology"])
            product_type: Filter by product type ("steel" or "iron")
            filename: Optional custom filename (auto-generated if None)
            export_csv: If True, also export chart data to CSV (default: True)

        Returns:
            Path to saved plot, or None if no data

        Raises:
            ValueError: If required columns are missing
        """
        # Validate required columns
        required_cols = ["furnace_group_id", "year", "product", column_name]
        missing_cols = [col for col in required_cols if col not in dataframe.columns]
        if missing_cols:
            raise ValueError(f"DataFrame missing required columns: {missing_cols}")

        # Check pivot columns exist
        for col in pivot_columns:
            if col not in dataframe.columns:
                raise ValueError(f"Pivot column '{col}' not found in DataFrame")

        dataframe = dataframe.copy()

        # Filter by product type and remove duplicates
        dataframe = dataframe.drop_duplicates(subset=["furnace_group_id", "year"])
        dataframe = dataframe[dataframe["product"] == product_type]

        if dataframe.empty:
            self.logger.warning(f"No data for product type '{product_type}' to plot")
            return None

        # Pivot to get a column for each region/technology
        df_pivot = dataframe.pivot_table(index="year", columns=pivot_columns, values=column_name, aggfunc="sum").fillna(
            0
        )

        if df_pivot.empty:
            self.logger.warning(f"No data after pivoting by {pivot_columns}")
            return None

        # Determine color map based on pivot columns
        # Only include colors for labels that actually exist in the data
        if pivot_columns == ["region"]:
            base_colours = self.config.region_colors if self.config.region_colors else region2colours
            legend_title = "Region"
        elif pivot_columns == ["technology"]:
            base_colours = self.config.tech_colors if self.config.tech_colors else tech2colours
            legend_title = "Technology"
        else:
            base_colours = {}
            legend_title = "_".join(pivot_columns)

        # Build color map for all columns that exist in the pivoted data
        # Pandas requires ALL columns to have colors if a color dict is provided
        colour_map: dict[str, Any] = {}
        colormap = cm.get_cmap("tab10")  # Default colormap for auto-assignment

        for idx, col in enumerate(df_pivot.columns):
            if col in base_colours:
                colour_map[col] = base_colours[col]
            elif pivot_columns == ["technology"]:
                # Use _ensure_tech_color for technologies not in the base map
                colour_map[col] = self._ensure_tech_color(col)
            else:
                # Auto-assign color for regions/other columns not in the base map
                colour_map[col] = colormap(idx % 10)

        # Create the plot
        fig, ax = plt.subplots(figsize=self.config.default_figsize_wide)

        df_pivot.plot(
            ax=ax,
            kind="area",
            stacked=True,
            color=colour_map,
            linewidth=0,
        )

        # Styling
        ax.set_title(title, fontsize=14, fontweight="bold")
        ax.set_xlabel("Year", fontsize=12)
        ax.set_ylabel(f"{column_name.replace('_', ' ').title()} [{units}]", fontsize=12)

        # Fix region/technology colors if needed (pandas sometimes doesn't apply them correctly)
        handles, labels = ax.get_legend_handles_labels()
        if pivot_columns == ["region"] or pivot_columns == ["technology"]:
            for handle, label in zip(handles, labels):
                if label in colour_map and hasattr(handle, "set_facecolor"):
                    handle.set_facecolor(colour_map[label])

        # Order legend top-to-bottom to match the visual stack - Excludes all-zero columns
        label_to_handle = {str(lbl): h for h, lbl in zip(handles, labels)}
        ordered_labels = [str(c) for c in self._legend_order_for_stack(df_pivot) if str(c) in label_to_handle]
        ordered_handles = [label_to_handle[lbl] for lbl in ordered_labels]
        self._style_legend(ax, title=legend_title, handles=ordered_handles, labels=ordered_labels)

        # Set x-axis to show only integer years
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))
        if not df_pivot.index.empty:
            ax.set_xlim(df_pivot.index.min(), df_pivot.index.max())

        ax.grid(True, alpha=self.config.grid_alpha, linestyle=self.config.grid_linestyle)

        # Ensure y-axis starts at 0
        self._ensure_y_axis_starts_at_zero(ax)

        fig.tight_layout()

        # Generate filename if not provided
        if filename is None:
            pivot_str = pivot_columns[0] if pivot_columns else "unknown"
            filename = f"{product_type}_{column_name}_development_by_{pivot_str}.png"

        # Export CSV if requested
        if export_csv:
            self._save_chart_data_to_csv(df_pivot, filename)

        return self._save_figure(fig, filename)
